source 'https://rubygems.org'
# gem "thin"
gem 'rails', '3.2.13'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'mysql2', '0.3.11'
# gem 'activerecord-mysql2-adapter'

gem 'omniauth'

#gem for facebook oauth
gem 'omniauth-facebook'
#gem for twitter oauth
gem 'omniauth-twitter'

#gem mailing system
gem 'mailboxer'
# gem for pagination for mailling system
gem 'will_paginate'
#gem for mailing system avatar img
gem 'gravatar_image_tag'

gem 'chosen-rails'
gem 'jquery-turbolinks'

#gem for advanced multiple field search
gem 'ransack'

#gem for send devise email in queueing process
gem 'delayed_job_active_record'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'turbo-sprockets-rails3'
  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
gem 'json', '~> 1.8.3'

gem 'activerecord-import', '~> 0.3.1'
gem 'therubyracer', :platforms => :ruby

gem 'carrierwave', '~>0.11.0'

#To get state of country
gem 'carmen-rails'

#For Grouping feature
gem 'groupify'

#For Commenting/Activity feature
gem 'acts_as_commentable_with_threading'

gem 'polyamorous', github: 'activerecord-hackery/polyamorous'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
gem 'devise'

gem 'private_pub'
gem 'thin'

#For image slider
gem 'bxslider-rails'
